# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\sourcecard.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sourcecard_ui(object):
    def setupUi(self, sourcecard_ui):
        sourcecard_ui.setObjectName("sourcecard_ui")
        sourcecard_ui.resize(143, 190)
        sourcecard_ui.setMinimumSize(QtCore.QSize(143, 190))
        sourcecard_ui.setMaximumSize(QtCore.QSize(143, 190))
        self.verticalLayout = QtWidgets.QVBoxLayout(sourcecard_ui)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(sourcecard_ui)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setStyleSheet("#frame\n"
"{\n"
"border: 2px solid #1296db;\n"
"border-radius:10px\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_source_name = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.label_source_name.sizePolicy().hasHeightForWidth())
        self.label_source_name.setSizePolicy(sizePolicy)
        self.label_source_name.setStyleSheet("font: 12pt \"小米兰亭\";")
        self.label_source_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_source_name.setObjectName("label_source_name")
        self.verticalLayout_3.addWidget(self.label_source_name)
        self.label_ = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.label_.sizePolicy().hasHeightForWidth())
        self.label_.setSizePolicy(sizePolicy)
        self.label_.setMaximumSize(QtCore.QSize(135, 135))
        self.label_.setText("")
        self.label_.setPixmap(QtGui.QPixmap(":/新前缀/sensor.png"))
        self.label_.setScaledContents(True)
        self.label_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_.setObjectName("label_")
        self.verticalLayout_3.addWidget(self.label_)
        self.frame_source_viewer = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_source_viewer.sizePolicy().hasHeightForWidth())
        self.frame_source_viewer.setSizePolicy(sizePolicy)
        self.frame_source_viewer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_source_viewer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_source_viewer.setObjectName("frame_source_viewer")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_source_viewer)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3.addWidget(self.frame_source_viewer)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(sourcecard_ui)
        QtCore.QMetaObject.connectSlotsByName(sourcecard_ui)

    def retranslateUi(self, sourcecard_ui):
        _translate = QtCore.QCoreApplication.translate
        sourcecard_ui.setWindowTitle(_translate("sourcecard_ui", "Form"))
        self.label_source_name.setText(_translate("sourcecard_ui", "传感器名称"))
import sourcecard_src_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sourcecard_ui = QtWidgets.QWidget()
    ui = Ui_sourcecard_ui()
    ui.setupUi(sourcecard_ui)
    sourcecard_ui.show()
    sys.exit(app.exec_())
